apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.webApp.spec.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: web-app
      env: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        app: web-app
        env: {{ .Values.namespace }}
    spec:
      containers:
      - name: nodejs-app
        image: {{ .Values.webApp.spec.image }}:{{ .Values.webApp.spec.imagetag }}
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef: 
              name: env-file-secrets
          - configMapRef: 
              name: env-file-configmap
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 75Mi
        readinessProbe:
          exec:
            command:
            - ls
            - node_modules
          # tcpSocket:
          #   port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          
              

          