apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: postgres
    env: {{ .Values.namespace }}
  ports:
  - port: 5432
    name: postgresql
    targetPort: 5432
