apiVersion: v1
kind: Secret
metadata:
  name: env-file-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
    PGPASSWORD: {{ .Values.secret.data.pgpassword }}
    COOKIE_ENCRYPT_PWD: {{ .Values.secret.data.cookie_encrypt_pwd }}
    OKTA_CLIENT_SECRET: {{ .Values.secret.data.okta_client_secret }}
