apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: web-app
    env: {{ .Values.namespace }}
  ports:
  - port: 80
    name: http
    targetPort : 8080
